### ISSUE TITLE
Remote Music Libraries

### ISSUE THREAD

**Issue by kanyi** [bradfitz/android-squeezer#5]
There is a plug-in in LMS the Remote Music Libraries.  I can use this for listening music across UPnP/DLNA connections. This is working well, on the LMS web interface. But unfortunately I did not see these option under the Squeezer. It is possible to create a menu for this?

**Comment by bradfitz** [comment]
Sorry, this repo is no longer the upstream home for squeezer. See its Play Store listing for the new maintainer's repo.
